### ISSUE TITLE
Cannot find module 'peer'

### ISSUE THREAD

**Issue by white-gecko** [KodeKraftwerk/reepio-peering-server#1]
When I try to start the peering-server in my docker environment I get the wollowing error:

    reepio-peering-server# npm start
    
    > reepio-peering-server@0.0.0-4 start /reepio-peering-server
    > node src/server.js
    
    module.js:338
        throw err;
              ^
    Error: Cannot find module 'peer'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/reepio-peering-server/src/server.js:6:12)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
    
    npm ERR! Linux 3.16.0-4-amd64
    npm ERR! argv "node" "/usr/local/bin/npm" "start"
    npm ERR! node v0.12.5
    npm ERR! npm  v2.11.3
    npm ERR! code ELIFECYCLE
    npm ERR! reepio-peering-server@0.0.0-4 start: `node src/server.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the reepio-peering-server@0.0.0-4 start script 'node src/server.js'.
    npm ERR! This is most likely a problem with the reepio-peering-server package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node src/server.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls reepio-peering-server
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /reepio-peering-server/npm-debug.log

**Comment by white-gecko** [comment]
After `npm install peer` also `q` and `winston` are missing

**Comment by korve** [comment]
Ok, thank you i'll look into it

**Comment by korve** [comment]
You'll have to run `npm install` before running it. I've updated the README.md
